Player.create(name: "henry", password: "henry")
Player.create(name: "jay", password: "jay")
Rival.create(name: "larry")
Rival.create(name: "eric")
Game.create(player_id: 1, rival_id: 1)
Game.create(player_id: 2, rival_id: 2)
Pokemon.create(name: "charmander")
Pokemon.create(name: "squirtle")
Pokemon.create(name: "mewtwo")
Pokemon.create(name: "bulbasaur")
Our.create(pokemon_id: 1, player_id: 1)
Our.create(pokemon_id: 2, player_id: 2)
Their.create(pokemon_id: 3, rival_id: 1)
Their.create(pokemon_id: 4, rival_id: 2)